### ISSUE TITLE
[FEATURE]: Achtergrond van pagina

### ISSUE THREAD

**Issue by RubenZW** [W-333/w-333.github.io#2]
De kleur op de achtergrond veranderen naar:

- [ ] #8587d5
- [ ] #627fff

**Comment by W-333** [comment]
**Kleuren:**
- #8587d5
- #627fff

**Comment by W-333** [comment]
Deze kleuren zijn kapot lelijk

**Comment by W-333** [comment]
![image](https://github.com/W-333/w-333.github.io/assets/134773245/8d0163f7-04c6-4118-ab33-fde61c94b021)
![image](https://github.com/W-333/w-333.github.io/assets/134773245/6284c5ce-d0a6-493e-8e03-82c898873321)

**Comment by RubenZW** [comment]
Jij bent lelijk

Op ma 29 mei 2023 18:31 schreef W-333 ***@***.***>:

**Comment by W-333** [comment]
Besproken word niet gemaakt

**Comment by W-333** [comment]
.
